### ISSUE TITLE
How to create multirooms or update a room from roomid

### ISSUE THREAD

**Issue by mboahost** [Xingtao/FFdynamic#12]
Hello, 

thank you for this fantastic tool. 
I'm trying to make a webui with nodejs using interactiveLive. But I'm facing an issue because it is impossible for the system to work multi users. is there a way to use multi users with this sytem? or it is just for one channel?

best regards.

**Comment by Xingtao** [comment]
Hi, currently it is just for one room. 
InteractiveLive is an demo to show the capacity of the library, but it is designed  to work in cluster mode ( a manager process needed and it is not implemented).

**Comment by jovial237** [comment]
@Xingtao thank you for the answer.
Is there a user guide to be able to write a custom cluster? For multiples rooms?

**Comment by Xingtao** [comment]
Unfortunately there is no user guide. 

You may check this commit for a reference:
```
31f2e90ff795caccd2b54abb46add28c0be736c4  -   add a small cluster manager
```
it is written in lua (using openresty with nginx) and is not finished.

Basically, manage process will do command receiving (http request from outside world) and dispatching(forward message to the corresponding InteractiveLive process), such as:
   1)  spawn new InteractriveLive process (one process as one task room);
   2)  stop InteractriveLive process (when task finish)
   3)  do bookkeeping works (such as: which InteractriveLive process related to which task room, http port, task status) and normally database needed here for bookkeepings.
   4) forward task status update message to proper task process:  layout change, backgroud change, mute-unmute, etc..

**Comment by mboahost** [comment]
Thank you @Xingtao will try and come back to this thread later. 
otherwise I encontred a memory issue while using the python testIal.py script. when creating a room with one rtmp input the service use too many memory. 
Thank you very murch.

**Comment by yacineb** [comment]
Hi,  do you mean a InteractiveLive process instance can only handle one room ? why does it have this limitation ? What's the point of create_room api ?

**Comment by Xingtao** [comment]
Hi, main purpose here is  to simplify implementation of 'ial', separate task management (room mangement、 resources management）out of ‘ial’.

Let's say there are some machines as a cluster provide 'ial' service.
It will be break down to 3 pieces:

1. Top level is for overall task schedule (cluster level, communicate with outside), find available node, create/stop task, etc.

2. Middle level manage is inside a node (machine level,  mainly for machine resources manage and spawn mutiple 'ial' processes or ial dockers). Because 'ial' could have multiple participant with different resolution and codec format, etc.., we can't know how much resources it may consume in prior.  So, to avoid run out of resources and be efficient usage of resources, it should use a machine level dynamic resources management here.

3. At last, it is 'ial' implementation, which just dealing with real video process, no other tasks.
   For create_room api to 'ial' implementation, it should be forward from Top level and Middle level management parts, with enough infos to create a task.
