### ISSUE TITLE
output to rtmp does not have video

### ISSUE THREAD

**Issue by yacineb** [Xingtao/FFdynamic#16]
Hello,

I've been testing davTests/streamletMixTest.cpp example and it works fine when the output is a file. Howver when i tried to change output url to rtmp (publish to local nginx_rtmp service) . 

I got only audio when i playback in vlc. for output file it's fine.

Is there an option i'm missing?  I just added this  muxOption2.set(DavOptionContainerFmt(), "flv"); to get output works however i still have no video

Thank you very much

**Comment by Xingtao** [comment]
Hi, can you change inputs to real time streams and have a try. Also make sure transcoding(mixing) process frame rate can reach real time.

**Comment by yacineb** [comment]
Finally it worked with video with the option set above in av dictionary. It seems that ffdynamic does not guess output fmt from uri scheme!

How can I ensure proceed frame rate can reach real-time ?? I'm sorry I'm still a noob to FFmpeg/libav

**Comment by Xingtao** [comment]
Normally depends on CPU capacity. For small resolution video, it can always reach real time. 
You can also log the instance fps.

**Comment by yacineb** [comment]
Thanks, has Interactive Live app been tested with rtmp inputs/outputs? 

Maybe I can reverse engineer it's code and inter stand what missing in the example..

**Comment by Xingtao** [comment]
Yes, Interactive Live is tested. Check its config file at:  apps/interactiveLive/ialConfig.json

**Comment by yacineb** [comment]
Interactive live example config and python file deal only with files in/outputs.
My question was about whether rtmp in/out has been tested in ial. Consuming/pushing to Rtmp is a very common scenario in production, however it's not so obvious with ffdynamic and there is not test case which covers it.

I found your tool interesting, code quality and comments are great. It shows great c++ skills.

However tests and documentation are missing in some "strategic" places, it would be great if you provide short example of mcu with rtmp/RTSP inputs/outputs 

Thank you very much

**Comment by Xingtao** [comment]
Hi, they can deal with any rtmp/hls/rtsp and many others input/output streams, these functionalities are made by FFmpeg.
To make use of those,  for instance,  rtmp input and output, one could:

1. in ialConfig.json, there is a field:  "output_settings".
   this field define output setting templates, for instance,  '720p_2000kb' is a output seting template;
  
```
 "output_settings" : {
    "720p_2000kb" : {
      "video_encode" : {
        "encode_type": "ffmpeg",
        "codec_name": "libx264",
        "fps_num" : 25,
        "fps_den" : 1,
        "avdict_encode_option": {"video_size" : "1280x720", "bufsize" : "2000k", "maxrate" : "2000k",
                                 "preset" : "fast", "g" : "60", "rc-lookahead" : "30"}
      },
      "audio_encode" : {
        "encode_type" : "ffmpeg",
        "codec_name" : "aac-he",
        "avdict_encode_option" : {"ac" : "2", "ab" : "128k", "ar" : "44100"}
      },

      "pre_encode_video_filter" : {},
      "pre_encode_audio_filter" : {"filter_type" : "ffmpeg",
                                     "filter_arg" : "acrossfade=d=10:o=0:c1=exp:c2=exp"},
      "mux_outputs" : [
        {"mux_type" : "ffmpeg", "mux_fmt" : "flv", "avdict_mux_option" : {}}
      ]
    }]
```
   in this  '720p_2000kb', set up mux fmt to flv (for rtmp output) by:
   ``` {"mux_type" : "ffmpeg", "mux_fmt" : "flv", "avdict_mux_option" : {}}```
   we can also add more muxer outputs, which in turn outputs several streams (same audio/video encoded stream, but different containers)


We can define a bunch of common use output settings for our own application.


Then when create a new task, pick one or several of these template, for instance, in testIal.py
···
def sendCreateRoom():
    create_room = ial_request.CreateRoom()
    create_room.room_id = "ial_test"
    create_room.input_urls.append(input1)
    # can add input here, or dynamically add input
    # create_room.input_urls.append()
    create_room.room_output_base_url = output_dir
    new_output = create_room.output_stream_infos.add()
    new_output.output_setting_id = out_setting_id_720p
    new_output.output_urls.append(fullurl_output_720)
···
here we use ‘out_setting_id_720p’  and an output url:  fullurl_output_720 (set this one to rtmp: rtmp://xxxx.xxx).
```    
    new_output.output_setting_id = out_setting_id_720p
    new_output.output_urls.append(fullurl_output_720)
```

That is done for a rtmp input and output.

Moreover,  we can add more outputs in a single task, produce different audio/video encoded streams
```
 new_output_2 = create_room.output_stream_infos.add()
 new_output_3 = create_room.output_stream_infos.add()
 new_output_2.output_setting_id = another_setting_2
 new_output_2.output_urls.append(another_output_url_2)
 new_output_3.output_setting_id = another_setting_3
 new_output_3.output_urls.append(another_output_url_3)
```

So, after set these up in config and testIal.py, just run testIal.py and 
1. send createRoom
2. add one input, then add another one, follows more. . .
3. do other command test: change layouy, mute/unmute one of the inputs, change mix backgroud with new jpeg, etc..
4. stop ial

For in real application, use http rest api instead of this testIal.py.


Hope this help.

**Comment by yacineb** [comment]
Thank you for this very clear explanation. I'll give you feedback once testing done
