### ISSUE TITLE
Recommended server hardware (ial)

### ISSUE THREAD

**Issue by yacineb** [Xingtao/FFdynamic#17]
Hi,
I was testing ffdynamic On a server without gpu. I've noticed a very high cpu usage. I guess this is due to encoding/decoding (video and audio) which is very resource intensive.
Is a server with gpu (nvidia) mandatory for production ?
Is the performance gain significative with gpu? I'm tipically using ffdynamic for mcu (video room ).

What is the recommended sizing (CPU/ram) for a server ? I have a high number of inputs per room (can reach 30)

GPU is very expensive and I'd like to make sure it's necessary for an acceptable performance before buying it

Thks

**Comment by Xingtao** [comment]
HI， it is somehow not that easy to use hardware accelaration in FFdynamic.

For FFdynamic part, one needs some coding efforts to make it running nvidia codec or QSV codec (including cuda or qsv scaling). FFmpeg already made these functionalities, but to chain them up in FFdynamic (using Hardware AVFrame) is not done.

For combing part, cuda combing is not implemented in FFdynamic, and using cpu to do this is not preferred, since data transfer from nvidia decoder to cpu, do combing, then transfer back to nvidia encoder, is time consuming. (QSV data transfer is even more time consuming then nvidia). 

The above parts are not that hard, but need a lot of coding efforts. And currently I am short of time to implement these features.

As hardware performance, I have used  many cards to do codec work, M5000, P5000, P4, RTX serial, and for now RTX4000 is a good choice.

**Comment by yacineb** [comment]
Thank you for your clear reply, starting from the current ffdynamic version, is it possible tu do decent mcu for 2 or 3 rooms at the same time with an average of 10 participants per room ?

Does the current docker shipping with nvidia software take advantage of gpu for encoding/decoding at least?

Is a 32cpu server fine for this  Usage? Did you do a load testing ?

What if I reduce video bandwidth , does this reduce cpu usage?

**Comment by Xingtao** [comment]
If use nvidia card, one needs 
1. compile FFmpeg with nvidia codec support (cuvid for decoder, nvenc for encoder)
2. modify code in FFdynamic, using AVHWFramesContext and related AVFrame for data transfer (considerable works here)
3. change config file, pass codec as cuvid and nvenc


MCU  benchmark for CPUs is mainly the same as codec benchemark, so refer to codec CPU benchmark for different resolution, bitrate,  encode algorithms(h264/h265, etc). (here is an example: https://openbenchmarking.org/showdown/pts/x264)
Scaling and Mixing do take some computaion, but much less than encode.

Some companies use CPU servers for MCU, although it costs  more comparing  with hardware codec, especialy in large scale.

**Comment by yacineb** [comment]
Sure GPU costs less at large scale , but not for manager dozens of conferences per day... Even a 50 Xeon Gold server is almost half price of a 8 cores server with nvidia Tesla.
